// <auto-generated />
using System;
using BTCPayServer.Plugins.JumpSeller.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.JumpSeller.Data.Migrations
{
    [DbContext(typeof(JumpSellerDbContext))]
    [Migration("20260227143636_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.JumpSeller")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.JumpSeller.Data.JumpSellerInvoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<string>("Amount")
                        .HasColumnType("text");

                    b.Property<bool>("CallbackSent")
                        .HasColumnType("boolean");

                    b.Property<string>("CallbackUrl")
                        .HasColumnType("text");

                    b.Property<string>("CancelUrl")
                        .HasColumnType("text");

                    b.Property<string>("CompleteUrl")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<string>("LastResult")
                        .HasColumnType("text");

                    b.Property<string>("OrderReference")
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.HasKey("InvoiceId");

                    b.ToTable("JumpSellerInvoices", "BTCPayServer.Plugins.JumpSeller");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.JumpSeller.Data.JumpSellerStoreSetting", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("EpgAccountId")
                        .HasColumnType("text");

                    b.Property<string>("EpgSecret")
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("JumpSellerStoreSettings", "BTCPayServer.Plugins.JumpSeller");
                });
#pragma warning restore 612, 618
        }
    }
}
