// <auto-generated />
using System;
using BTCPayServer.Plugins.GhostPlugin;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.Plugins.GhostPlugin.Data.Migrations
{
    [DbContext(typeof(GhostDbContext))]
    partial class GhostDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.Plugins.Ghost")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.Plugins.GhostPlugin.Data.GhostMember", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("MemberId")
                        .HasColumnType("text");

                    b.Property<string>("MemberUuid")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("text");

                    b.Property<string>("TierId")
                        .HasColumnType("text");

                    b.Property<string>("UnsubscribeUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GhostMembers", "BTCPayServer.Plugins.Ghost");
                });

            modelBuilder.Entity("BTCPayServer.Plugins.GhostPlugin.Data.GhostSetting", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AdminApiKey")
                        .HasColumnType("text");

                    b.Property<string>("AdminDomain")
                        .HasColumnType("text");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<string>("ContentApiKey")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("IntegratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShopName")
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<string>("StoreName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("GhostSettings", "BTCPayServer.Plugins.Ghost");
                });
#pragma warning restore 612, 618
        }
    }
}
